
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost 
  username: arthur
  password: arthur

development:
  <<: *default
  database: fleet_project_development

test:
  <<: *default
  database: fleet_project_test
